[workflow]
name = 'Annotate_Clinvar'
scatter_count = 50
vcf_size_in_gb = 30
sequencing_type = 'genome'

[hail]
cancel_after_n_failures = 1
default_timeout = 18000
default_memory = 'highmem'

[images]
vep = 'australia-southeast1-docker.pkg.dev/cpg-common/images/vep:105.0'
cpg_workflows = 'australia-southeast1-docker.pkg.dev/cpg-common/images/cpg_aip:1.1.1'

[clinvar]
filter_benign = ['illumina laboratory services; illumina']

[cohorts]
placeholder = "placeholder"
