[buckets]
web_suffix = 'web'
tmp_suffix = 'tmp'
analysis_suffix = 'analysis'

[workflow]
name = 'AIP'
scatter_count = 50
sequencing_type = 'genome'

[moi_tests]
description = 'thresholds for different filters during the MOI checks'
gnomad_dominant = 0.001
gnomad_max_homs_dominant = 0
gnomad_max_homs_recessive = 1
gnomad_max_ac_dominant = 10
gnomad_max_hemi = 1

[csq]
description = 'variables affecting how the VCF variants are parsed, and AnalysisVariant objects are populated'
csq_string = ['consequence', 'symbol', 'gene', 'feature', 'mane_select', 'biotype', 'exon', 'hgvsc', 'hgvsp', 'variant_class', 'ensp', 'lof']

[filter]
description = 'variables for the hail operations, including CSQ sets and filter thresholds'
ac_threshold = 0.01
additional_csq = [ 'missense_variant']
af_semi_rare = 0.01
cadd = 28.1
critical_csq = [ 'frameshift_variant', 'splice_acceptor_variant', 'splice_donor_variant', 'start_lost', 'stop_gained', 'stop_lost', 'transcript_ablation',]
gerp = 1.0
eigen = 0.25
polyphen = 0.99
revel = 0.77
sift = 0.0
spliceai = 0.5

[hail]
cancel_after_n_failures = 1
default_timeout = 6000
default_memory = 'highmem'
private_clinvar = 'gs://cpg-acute-care-test/clinvar_01-01-2022/clinvar_reprocessed.ht'

[images]
vep = 'vep:105.0'
gatk = 'gatk:4.2.6.1'
cpg_workflows = 'australia-southeast1-docker.pkg.dev/cpg-common/images/cpg_workflows:latest'
hail = 'australia-southeast1-docker.pkg.dev/cpg-common/images/cpg_workflows:latest'
picard = 'picard_samtools:v0'
picard_samtools = 'picard_samtools:v0'

[references]
vep_mount = 'vep/105.0/mount'
genome_build = 'GRCh38'

[references.broad]
prefix = 'hg38/v0'
ref_fasta = 'dragen_reference/Homo_sapiens_assembly38_masked.fasta'
genome_calling_interval_lists = 'wgs_calling_regions.hg38.interval_list'

[references.seqr]
prefix = 'seqr/v0-1'
combined_reference = 'combined_reference_data_grch38-2.0.4.ht'
clinvar = 'clinvar.GRCh38.ht'
