[workflow]
dataset = "COHORT"

[cohorts.COHORT]
description = "variables specific to this cohort, but not specific to genome/exome"
cohort_panels = [1, 2, 3]
forbidden = "path to a list of forbidden genes"

[cohorts.COHORT.genome]
description = "variables specific to the genome/exome cohort"
seqr_lookup = "e.g. gs://cpg-COHORT-test/reanalysis/parsed_seqr.json"
external_labels = "path to labels file"
seqr_instance = "e.g. https://seqr.populationgenomics.org.au"
seqr_project = "e.g. COHORT_project_id"
