name: 'clinvar summary runner'

on:
  workflow_dispatch: {}

  schedule:
    - cron: '42 1 1 * *'

permissions:
  id-token: write

jobs:
  run_clinvar_batch:
    runs-on: ubuntu-latest

    steps:

      - id: "google-cloud-auth"
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/847315747340/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github@cpg-talos.iam.gserviceaccount.com"

      - id: "google-cloud-sdk-setup"
        name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1

      - name: "Submit report crawler"
        run: |
          TOKEN=$(gcloud auth print-identity-token --impersonate-service-account="github@cpg-talos.iam.gserviceaccount.com" --audiences="https://server-a2pko7ameq-ts.a.run.app" --include-email)
          curl --fail --silent --show-error -X POST \
              -H "Authorization: Bearer $TOKEN" \
              -H "Content-Type:application/json" \
              -d '{"output": "generate_clinvar_${{ steps.date.outputs.date }}", "dataset": "talos", "accessLevel": "full", "repo": "automated-interpretation-pipeline", "commit": "${{ github.sha }}", "cwd": "reanalysis", "script": ["./clinvar_runner.py"], "description": "Generate Latest Clinvar Summaries", "image": "australia-southeast1-docker.pkg.dev/cpg-common/images/cpg_aip:2.0.0", "config": {"workflow": {"sequencing_type": "genome"}, "cohorts": {"talos": {"clinvar_filter": ["victorian clinical genetics services, murdoch childrens research institute"]}}}, "wait": false}' \
              https://server-a2pko7ameq-ts.a.run.app
