name: CI_test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: requirements*.txt

    - name: Install packages
      run: |
        pip install .[full,test]

    - name: test
      run: pytest -n auto .
